### ISSUE TITLE
crc-usage.pl error

### ISSUE THREAD

**Issue by fangpingmu** [pitt-crc/wrappers#29] opened 2022-06-06 13:06 UTC
https://crc.pitt.edu/node/10935

```
crc-usage.pl

Traceback (most recent call last):

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context

context)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute

cursor.execute(statement, parameters)

sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/ihome/crc/bank/crc_bank.py", line 518, in

utils.account_exists_in_table(proposal_table, args[""])

File "/ihome/crc/bank/utils.py", line 96, in account_exists_in_table

q = table.find_one(account=account)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/dataset/table.py", line 487, in find_one

if not self.exists:

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/dataset/table.py", line 41, in exists

return self.name in self.db

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/dataset/database.py", line 147, in __contains__

return normalize_table_name(table_name) in self.tables

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/dataset/database.py", line 142, in tables

return self.inspect.get_table_names(schema=self.schema)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 201, in get_table_names

self.bind, schema, info_cache=self.info_cache)

File "", line 2, in get_table_names

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache

ret = fn(self, con, *args, **kw)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1160, in get_table_names

rs = connection.execute(s)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 942, in execute

return self._execute_text(object, multiparams, params)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text

statement, parameters

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context

context)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception

exc_info

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause

reraise(type(exception), exception, tb=exc_tb, cause=cause)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise

raise value.with_traceback(tb)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context

context)

File "/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute

cursor.execute(statement, parameters)

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"] (Background on this error at: [http://sqlalche.me/e/e3q8](https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsqlalche.me%2Fe%2Fe3q8&data=05%7C01%7Ccrchd%40pitt.edu%7C00da6a3575b6433b4dae08da47099943%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637900403799382229%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=urABuMPhifyGMOL%2FTFY1cdNFTxfu%2F1KSNfpeBk6U8Ys%3D&reserved=0))
```

**Comment by djperrefort** [comment] 2022-06-06 13:25
I can run the script with no problem so I'm wondering if this is a permissions problem.

Looking at the traceback, I see 

```
attempt to write a readonly database
```

This almost makes sense given the permissions on the wrapper script and the database:

```bash
-rwxr-xr-x  1 bmooreii sam 2002 Aug 11  2020 crc-usage.pl
-rw-r--r--  1 djp81   sam 98304 Jun  4 15:19 crc_bank.db
```

Those permissions look exactly like I expect them to. My real question is why the wrapper is requesting write access? The SQL statement should be read only:

```sql
SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
```

**Comment by djperrefort** [comment] 2022-06-06 13:37
No, git shouldn't change any permissions on its own. I wasn't sure if you changed permissions for just `.git` or for other files as well.

I agree the problem is stemming from permissions tied to executing `crc_bank.py`. 

It looks like the file permissions are set correctly. The user can read/execute the scripts. However, the script is requesting write access for some reason (which we definitely cannot give).

I don't understand:
1) Why is write access even necessary?
2) Has it always been necessary?
    1) If not, what changed? 
    2) If so, why hasn't this been reported before?

**Comment by djperrefort** [comment] 2022-06-06 14:23
This is looking more like a permissions issue at the database level. After switching to a different user account I get the following:

```sql
$ sqlite3

sqlite> attach "/ihome/crc/bank/crc_bank.db" as db;
Error: unable to open database file
```

For what its worth, WAL is enabled so it's not a multiple connections issue:

```sqlite
sqlite> PRAGMA db.journal_mode;
wal
```

**Comment by Comeani** [comment] 2022-06-06 15:04
If it's permissions, I feel like the root cause had to be the chmod... Perhaps the permissions were changed to 644 from something else as a downstream effect? https://stackoverflow.com/q/7163736/15928140

Is it possible the DB requires different permissions if being accessed through a python script?

**Comment by djperrefort** [comment] 2022-06-06 15:06
> Is it possible the DB requires different permissions if being accessed through a python script? 

The same permissions apply, although the user executing the script can sometimes change. I don't think that's the case here though since we get an `Error: unable to open database file` message when working directly in SQL.

**Comment by djperrefort** [comment] 2022-06-06 15:17
It's clearly not a database locking issue, but I rotated the database file a little while ago anyways. As expected, the issue is unfixed.

**Comment by djperrefort** [comment] 2022-06-06 15:44
@fangpingmu  - [I have the same question](https://github.com/pitt-crc/wrappers/issues/29#issuecomment-1147444618). At first, I thought it was part of a concurrent connection issue, but I think we've sadly eliminated that as the potential cause (as outlined in the above thread).

**Comment by djperrefort** [comment] 2022-06-06 20:29
The problem should be fixed now. It looks like `wal` mode was enabled on the database sometime on Friday. I'm not sure by who or what, but the database mode has been updated and the problem seems to have disappeared.

**Closed by djperrefort** 2022-06-06 20:29 UTC
